name: Publish Docker image
on:
  # it will be triggered by release
  #  release is based on tag
  release:
    types: [published]
jobs:
  publish_package:
    name: Publish electron package
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: show ls and pwd
        run: |
          ls
          pwd
      - name: install packages
        run: npm install
      - name: Publish release
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check artifacts
        run: ls /Users/runner/work/electron-react-template/electron-react-template/dist
      - uses: actions/upload-artifact@v3
        with:
          name: react-electron-app.app
          path: /Users/runner/work/electron-react-template/electron-react-template/dist/mac/react-electron-app.app
